### ISSUE TITLE
broken in MacOS Sequoia

### ISSUE THREAD

**Issue by rlschroeder** [cmer/lg-tv-control-macos#59]
lgtv can't seem to access the local network in Sequoia - probably has to do with the new Local Network Permissions, and it's not possible to manually add applications.

https://apple.stackexchange.com/questions/475737/how-can-i-manually-allow-local-network-access-for-an-app

**Comment by rlschroeder** [comment]
Right - it actually may be something else, looking at the output from terminal. Let's see: I updated MacOS, and also the firmware on the LG OLED recently. I tried to reinstall LG TV Control with the install script.

I'm sucessfully able to run '~/bin/lgtv --name MyTV --ssl swInfo'

However, when I run '~/bin/lgtv --name MyTV --ssl screenOff' I receive the following output:

Traceback (most recent call last):
  File "/Users/ryans/bin/lgtv", line 33, in <module>
    sys.exit(load_entry_point('LGTV==0.3', 'console_scripts', 'lgtv')())
  File "/Users/ryans/.local/share/mise/installs/python/3.8.18/lib/python3.8/site-packages/LGTV-0.3-py3.8.egg/LGTV/__init__.py", line 193, in main
  File "/Users/ryans/.local/share/mise/installs/python/3.8.18/lib/python3.8/site-packages/ws4py-0.5.1-py3.8.egg/ws4py/client/__init__.py", line 217, in connect
  File "/Users/ryans/.local/share/mise/installs/python/3.8.18/lib/python3.8/ssl.py", line 1375, in connect
    self._real_connect(addr, False)
  File "/Users/ryans/.local/share/mise/installs/python/3.8.18/lib/python3.8/ssl.py", line 1366, in _real_connect
    self.do_handshake()
  File "/Users/ryans/.local/share/mise/installs/python/3.8.18/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by rlschroeder** [comment]
Welp, after all that, the reinstall and a reboot seemed to fix it.
