### ISSUE TITLE
TV not turning on despite reporting so 

### ISSUE THREAD

**Issue by KnifeWrench** [cmer/lg-tv-control-macos#68]
Using a 2024 MacBook Pro MacOS Sequoia with the lid closes (similar behavior with lid open). When it goes to sleep, this works beautifully. Trying to wake it on the other hand is less successful. According to the logs when the lid is open the TV turns back on, sets the hdmi input and switches it to pc mode, however the the TV does not actually turn on.

Same behavior with the lid closed apart from the logs are a bit more honest.  

Lid open:
```
2024-12-30 23:38:45: Starting LGTV watcher...
2024-12-30 23:38:45: -- Done.
2024-12-30 23:50:06: Received event: 1
2024-12-30 23:50:06: Received event: 3
2024-12-30 23:50:06: TV is connected and going to sleep
2024-12-30 23:50:06: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-30 23:50:07: TV is currently on input com.webos.app.hdmi2
2024-12-30 23:50:07: TV is configured to prevent sleep when using other input? true
2024-12-30 23:50:07: Computer should be connected to input HDMI_2
2024-12-30 23:50:07: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-30 23:50:07: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  power_off
2024-12-30 23:50:08: TV screen was turned off with command `power_off`.
2024-12-30 23:50:08: Received event: 10
2024-12-30 23:50:32: Received event: 4
2024-12-30 23:50:32: Wake on LAN packet sent to 20:28:BC:**:**:**
2024-12-30 23:50:32: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  turn_screen_on
2024-12-30 23:50:35: TV was turned on
2024-12-30 23:50:35: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-30 23:50:36: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  launch_app com.webos.app.hdmi2
2024-12-30 23:50:37: TV input switched to com.webos.app.hdmi2
2024-12-30 23:50:37: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  set_device_info HDMI_2 pc 'Mac'
2024-12-30 23:50:38: TV was set to PC mode
2024-12-30 23:50:38: Received event: 0
2024-12-30 23:50:38: Wake on LAN packet sent to 20:28:BC:**:**:**
2024-12-30 23:50:38: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  turn_screen_on
2024-12-30 23:50:38: TV was turned on
2024-12-30 23:50:38: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-30 23:50:39: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  set_device_info HDMI_2 pc 'Mac'
2024-12-30 23:50:40: TV was set to PC mode
2024-12-30 23:50:40: Received event: 11
2024-12-30 23:50:40: Wake on LAN packet sent to 20:28:BC:**:**:**
2024-12-30 23:50:40: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  turn_screen_on
2024-12-30 23:50:41: TV was turned on
2024-12-30 23:50:41: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-30 23:50:41: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  set_device_info HDMI_2 pc 'Mac'
2024-12-30 23:50:42: TV was set to PC mode

```

Lid closed:
```
2024-12-31 00:01:48: Received event: 1
2024-12-31 00:01:48: Received event: 3
2024-12-31 00:01:48: TV is connected and going to sleep
2024-12-31 00:01:48: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-31 00:01:49: TV is currently on input com.webos.app.hdmi2
2024-12-31 00:01:49: TV is configured to prevent sleep when using other input? true
2024-12-31 00:01:49: Computer should be connected to input HDMI_2
2024-12-31 00:01:49: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  get_current_app
2024-12-31 00:01:50: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.0.113  power_off
2024-12-31 00:01:51: TV screen was turned off with command `power_off`.
2024-12-31 00:01:51: Received event: 10
2024-12-31 00:02:07: Received event: 11
2024-12-31 00:02:07: Received event: 0
2024-12-31 00:02:07: Received event: 4
```

**Comment by cmer** [comment]
Did you enable Wake on LAN as mentioned [here](https://github.com/cmer/lg-tv-control-macos/blob/main/README.md)? This might be your issue.

**Comment by KnifeWrench** [comment]
Yup followed the readme initially, but obvs double checked. Both wake on LAN and the mobile one are on.

Debugging the script I could see that when lid was closed lgtv_is_connected() was returning false as soon as the the machine and tv entered sleep. I had wifi and lan both connected. Disconnecting wifi fixed this (for the most part, would still sometimes disconnect) meaning it was now behaving the same lid open or closed. Not the actual issue but nice.

Also in lgtv_exec_command I think you need to have _if rc == 0 instead_ of _if rc == nil_

**Comment by PylotLight** [comment]
This is also happening for me, I was previously using the windows app which worked fine for turning off and on.
Now using this mac version, turn off seems to work fine, but it does not turn on, despite the logs suggesting that it is.

```
2025-01-17 11:19:17: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.1.5  turn_screen_on
2025-01-17 11:19:18: TV was turned on
2025-01-17 11:19:18: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.1.5  get_current_app
2025-01-17 11:19:19: Executing command: ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.1.5  set_device_info HDMI_1 pc 'Mac'
2025-01-17 11:19:20: TV was set to PC mode
```

**Comment by cmer** [comment]
Can you try running the command directly from the terminal to see if there's a hint?

**Comment by cmer** [comment]
Try installing the new version. I improved logging a little bit.

**Comment by PylotLight** [comment]
```
TV on:
❯ ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.1.5  turn_screen_on
Traceback (most recent call last):
  File "/private/var/folders/l7/qqxmqd5170nfkmjpgpzjx6cc0000gn/T/tmp.2qwVc3ZXId/venv/bin/bscpylgtvcommand.py", line 8, in <module>
  File "bscpylgtv/utils.py", line 111, in bscpylgtvcommand
  File "asyncio/runners.py", line 194, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 721, in run_until_complete
  File "bscpylgtv/utils.py", line 18, in runloop
  File "bscpylgtv/webos_client.py", line 886, in turn_screen_on
  File "bscpylgtv/webos_client.py", line 671, in request
bscpylgtv.exceptions.PyLGTVCmdError: {'type': 'error', 'id': 0, 'error': '500 Application error', 'payload': {'returnValue': False, 'state': 'Active', 'errorCode': '-102', 'errorText': "The current sub state must be 'screen off'"}}
[PYI-45869:ERROR] Failed to execute script 'bscpylgtvcommand' due to unhandled exception!

TV off:
~ 
❯ ~/bin/bscpylgtvcommand -p ~/.aiopylgtv.sqlite 192.168.1.5  turn_screen_on
Traceback (most recent call last):
  File "/private/var/folders/l7/qqxmqd5170nfkmjpgpzjx6cc0000gn/T/tmp.2qwVc3ZXId/venv/bin/bscpylgtvcommand.py", line 8, in <module>
  File "bscpylgtv/utils.py", line 111, in bscpylgtvcommand
  File "asyncio/runners.py", line 194, in run
  File "asyncio/runners.py", line 118, in run
  File "asyncio/base_events.py", line 721, in run_until_complete
  File "bscpylgtv/utils.py", line 17, in runloop
  File "bscpylgtv/webos_client.py", line 150, in connect
  File "bscpylgtv/webos_client.py", line 199, in connect_handler
  File "websockets/asyncio/connection.py", line 313, in recv
websockets.exceptions.ConnectionClosedError: received 1008 (policy violation) Try Again Later (EWS); then sent 1008 (policy violation) Try Again Later (EWS)
[PYI-45947:ERROR] Failed to execute script 'bscpylgtvcommand' due to unhandled exception!
```

**Comment by cmer** [comment]
@PylotLight Looks like the TV is rejecting the request. See: https://www.perplexity.ai/search/i-m-trying-to-turn-on-and-off-fuEMHdyLR6SgnHJLD4ICIg

**Comment by cmer** [comment]
I just pushed out a pretty big update which should hopefully resolve these issues. Let me know!

**Comment by PylotLight** [comment]
Ok sweet it does look like thats improved.
1. The screen turns on as requested
2. However, I'm noticing the off functionality isn't working.. it's going to no signal instead of turning off, which is not super ideal.
3. I know it's possible to turn off and fully turn on again, while I am on wireless and I can test wired, 
it should also be possible with wireless as windows worked fine.

**Comment by cmer** [comment]
What TV are you using? I have a C2. Mine works as expected. I'm on a desktop Mac though. Previously Mac Studio, now Mac Mini. I wonder if we're on a different firmware.

FYI I changed `power_off` to `screen_off` to fix the policy error. 

I'll look into the log spam.

**Comment by PylotLight** [comment]
> What TV are you using? I have a C2
I have a C4
> 
> FYI I changed `power_off` to `screen_off` to fix the policy error. 
Will test later
> I fixed the "log spam".
Thanks!

Thanks again for your work on this one, good to make sure there's a solution for this on all platforms :D

**Comment by PylotLight** [comment]
hmm yep, looks like I can currently choose between auto screen off, or auto screen on but not both. 
I'm certain it worked via windows version so curious why the script fails for the same thing. Might try look at the Windows version to compare at some point.
Cheers for your efforts for now.

**Comment by PylotLight** [comment]
webOS24 / 9.2.2.2-1805 (latest)

**Comment by PylotLight** [comment]
what difference does that make?
Should be basically the same controls no?
Anything I should test/check from my side to see if something has changed?

**Comment by cmer** [comment]
I'm on the latest WebOS and everything works as it should.
